title: Hugbig Photography
email: your-email@domain.com
description: >
  The meanings are countless. We at Hug Big Photography believe that hugging especially means to ACCEPT all that you have— your friends, family and even your self— with a BIG heart.
baseurl:
url:

# Build settings
markdown: kramdown

sass:
    style: compressed

collections:
  gallery:
    output: true
    permalink: /gallery/:path/

cover:
  - rank: 1
    image: "item-1"

  - rank: 2
    image: "item-2"

  - rank: 3
    image: "item-3"

  - rank: 4
    image: "item-4"

  - rank: 5
    image: "item-5"

  - rank: 6
    image: "item-6"

  - rank: 7
    image: "item-7"


team:
  - name: AP YAO
    image: "apyao"
    role: "Editor/Portraits/<br/>Landscapes/Lay-out"

  - name: Alfred Adrian Yao
    image: "alfredyao"
    role: "Editor/Portraits/<br/>Candids"

  - name: Hero Redila
    image: "heroredila"
    role: "Portraits/Candids/<br/>Landscapes"


social-media:
  - image: "instagram"
    link: "https://www.instagram.com/hugbigphotography/"

  - image: "youtube"
    link: "https://www.youtube.com/channel/UC6_boFg_uWSn6Yst68AOM3A/videos"

  - image: "facebook"
    link: "https://www.facebook.com/hugbigphotography/"

button-filter:

  - id: 1
    name: Wedding
    filter: "wedding"

  - id: 2
    name: Engagement
    filter: "engagement"

  - id: 3
    name: Debut
    filter: "pre-debut"

  - id: 4
    name: Fashion
    filter: "fashion"




